### ISSUE TITLE
paquet debian IPXE

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/sambaedu-ipxe#2]
Le paquet debian génère des fichiers de boot avec les mauvaise options : 

* pas de console graphique
* clavier us
* pas de menu
* pas de user-agent pour différencier boot depuis kvm

Recompiler le paquet debian avec les bonnes options.

il faut ajouter dans debian/config les fichiers  .h d'origine modifiés avec les bonnes options.

**Comment by mollef** [comment]
J'avais noté ça 
https://github.com/SambaEdu/sambaedu-ipxe#mise-en-place-%C3%A0-la-mano

et donc la possibilité d'utiliser https://rom-o-matic.eu permettant de générer l'image qui nous intéresse avec les options qui vont bien. Reste ensuite de la mettre dans le paquet

**Comment by denis-b** [comment]
Le 01/04/2018 à 23:03, mollef a écrit :
>
> J'avais noté ça
> https://github.com/SambaEdu/sambaedu-ipxe#mise-en-place-%C3%A0-la-mano
>
> et donc la possibilité d'utiliser https://rom-o-matic.eu permettant de 
> générer l'image qui nous intéresse avec les options qui vont bien. 
> Reste ensuite de la mettre dans le paquet
>
>

Salut,

J'ai vu, et en  fait on peut refaire facilement le paquet debian avec 
les bonnes options pour les rom. C'est plus propre. Je vais le faire... 
et comme cela on aura le paquet complet, et donc il y aura le support uefi !

pour dhcp le module ldap ne convient pas, car il faut un schéma 
spécifique. On laisse tomber.
J'ai refait la conf dhcp. un script bash se charge de la partie statique 
de la conf, et  lancera si il existe un script php qui lira les 
reservations dans AD.  Comme cela on fera tout ce qui concerne les 
reservatinos en php c'est bien plus propre... Lors de la migration si on 
copie la partie du dhcp.conf contenant les reservations dans un ficiher 
reservations.conf, il sera pris en compte en attendant que le php 
fonctionne.


J'ai commité 2-3 trucs...

A+

Denis

**Comment by mollef** [comment]
Le paquet suivant est-il finalisé ? Si oui je ferme l'issue
```
apt-cache policy ipxe
ipxe:
  Installé : 1.0.0+git-20161027.b991c67-1sambaedu1
  Candidat : 1.0.0+git-20161027.b991c67-1sambaedu1
 Table de version :
 *** 1.0.0+git-20161027.b991c67-1sambaedu1 500
        500 http://wawadeb.crdp.ac-caen.fr/debian stretch/se4XP amd64 Packages
        100 /var/lib/dpkg/status
     1.0.0+git-20161027.b991c67-1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages

```
